---
title: "Untitled"
output: html_document
date: "2025-05-23"
---

```{r}
#Data Preparation (National Network)
#library(readxl)
#Author_Network <- read_excel("~/Dokumente/Studium Bachelor Sport und Leistung/Bachelorarbeit/Network_Author_Analysis.xlsx")


```

```{r}
#library(tidyverse)
# transform wide author network into a long author network for further analysis f.e. for gephi (Network Analysis)
#Author_Network_edited <- Author_Network %>% select(- publication_id, -year)
#Long Format
#Author_Network_long <- Author_Network_edited %>%
  #pivot_longer(
    #cols = starts_with("author_"),    # alle Spalten, die mit 'author_' beginnen
    #names_to = "author_position",     # neue Spalte mit dem ursprünglichen Spaltennamen
    #values_to = "author"              # neue Spalte mit dem Namen des Autors
  #) %>%
  #filter(!is.na(author) & author != "")

#export data file 
#library(openxlsx)
#write.xlsx(Author_Network_long, file = "~/Dokumente/Studium Bachelor Sport und Leistung/Bachelorarbeit/Network_Author_Analysis_long.xlsx")
```

```{r}
# Load data with nationality per author
library(readxl)
Author_Network_long_Nationality <- read_excel("~/Dokumente/Studium Bachelor Sport und Leistung/Bachelorarbeit/Network_Author_Analysis_Nationality.xlsx")


```


```{r}
#count unique authors (delete doubles of authors)
unique_authors <- unique(Author_Network_long_Nationality$author)
num_unique_authors <- length(unique_authors)

# output
cat("Anzahl unterschiedlicher Autoren:", num_unique_authors, "\n")
```
```{r}
# frequency of authors 
author_counts <- Author_Network_long_Nationality %>%
  count(author, sort = TRUE)

# output
print(author_counts)

author_counts %>% filter(n > 1)

## G. and N. Andrienko have only two publications!!!
```

```{r}
# count the number of authors per nationality
library(dplyr)

nationality_counts <- Author_Network_long_Nationality %>%
  group_by(nationality) %>%
  summarise(count = n_distinct(author)) %>%
  arrange(desc(count))

print(nationality_counts)

```




